### ISSUE TITLE
Alignment Cycle Layout: Link Groups

### ISSUE THREAD

**Issue by wjrl** [wjrl/AlignmentPlugin#4]
After performing an Alignment Cycle Layout, if you open the Link Groups dialog, it says "Order Network" instead of "Order Node". But the alignment was done "Order Node". What is up with that?

**Comment by RishiDesai** [comment]
Plugin Data has now knowledge of LayoutMode, so the LinkGroupSetUp dialogue does not know what the mode is. (I only perused the code so I might be wrong, but will look into it in a bit.)

**Comment by wjrl** [comment]
The relayout build data is being set correctly, but this information is not being propagated back into the network. I am digging in a bit myself.

**Comment by wjrl** [comment]
It's fixed in the next commit. Actually a fix in BioFabric core.
