### ISSUE TITLE
Default JS for correctness is too low

### ISSUE THREAD

**Issue by wjrl** [wjrl/AlignmentPlugin#5]
Default value is 0.1... it should be something more stringent, like 0.8

**Comment by RishiDesai** [comment]
OK. (I played around with JS thresholds and on average JS sim between nodes is rather low. For Example, for Yeast2K-SC perfect alignment, if I set it to .5 hardly like 20 nodes were denoted correct.)

**Comment by RishiDesai** [comment]
OK. I'll set it to .75. I feel like 1/4 is a good balance.

**Comment by wjrl** [comment]
Merged.
